server {
    listen 80;
    root /app;
    index index.html;

    location /api/ {
        proxy_pass http://dbrxz53b3lq3sfv2sp918cof.178.104.147.61.sslip.io/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host dbrxz53b3lq3sfv2sp918cof.178.104.147.61.sslip.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    location /socket.io/ {
        proxy_pass http://dbrxz53b3lq3sfv2sp918cof.178.104.147.61.sslip.io/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host dbrxz53b3lq3sfv2sp918cof.178.104.147.61.sslip.io;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
